---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>

name: fedora-hyprland-nvidia-extras

description: A custom Atomic Fedora image with Hyprland WM, NVIDIA/CUDA drivers, development tools, and more.

base-image: ghcr.io/ublue-os/base-nvidia
image-version: 42

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: bling
    install:
      - negativo17
  - type: dnf
    repos:
      files:
        - https://src.fedoraproject.org/rpms/fedora-repos/raw/f42/f/fedora-cisco-openh264.repo
      copr:
        - atim/starship
        - solopasha/hyprland
      #nonfree: negativo17
    install:
      allow-erasing: true
      packages:
        - xorg-x11-server-Xorg
        - xorg-x11-server-Xwayland
        - xorg-x11-nvidia
        - hyprland
        - hyprland-devel

        - satty

        - cuda-devel

        # LY DEPS
        #- kernel-devel
        #- pam-devel 
        #- libxcb-devel

        #- greetd
        #- tuigreet

        # Virtualization Tools
        - libvirt # Virtualization library and daemon
        - virt-install # Command line tool for installing VMs

        - bottles

        # Alternative Terminal and Text Editor
        - starship
        - conda

        # Multimedia Codecs and Thumbnail Generators
        - ffmpeg
        - gstreamer1
        - gstreamer1-plugin-libav # FFmpeg plugin for GStreamer
        - libvkd3d
        #- intel-media-driver # RPMFUSION Intel Media Driver for VAAPI (if you have Intel iGPU)

        - openh264 # Cisco OpenH264 codec

        # Thumbnailers
        - ffmpegthumbnailer
        - tumbler

        # Packages for working with Apple Devices
        - usbmuxd
        - libimobiledevice-utils
        - ifuse 

        - android-tools

        # Extensive Development Extras
        - make
        - gcc
        - git
        - cmake
        - htop
        - nano
        - helix
        - gdb
        - valgrind
        - strace
        - ltrace
        - pkgconf-pkg-config
        - zlib-devel
        - bzip2-devel
        - xz-devel
        - openssl-devel
        - elfutils-libelf-devel
        - libffi-devel
        - readline-devel
        - ncurses-devel
        - usbutils
        - lshw
        - pciutils
        - ddrescue
        - docker
        - podman

    remove:
      packages:
        #- mesa-libGL
        #- mesa-dri-drivers
        - noopenh264

  - type: files
    files:
    - source: finish-setup.sh
      destination: /var/usrlocal/finish-setup.sh
    - source: finish-setup.service
      destination: /etc/systemd/system/finish-setup.service

    - source: greetd-config.toml
      destination: /etc/greetd/config.toml

  
#  - type: script
#    scripts:
#      - install-ly.sh

  - type: systemd
    system:
      enabled:
        - libvirtd.service
        #- greetd.service
        #- ly.service
        - finish-setup.service

  - type: default-flatpaks
    system:
      install:
        #- org.videolan.VLC
        - org.mozilla.firefox
        - org.chromium.Chromium
        #- com.github.tchx84.Flatseal
        #- org.fedoraproject.MediaWriter
    user:
      install:
        - com.usebottles.bottles

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly

  - type: signing



#- https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
#- https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
#- https://negativo17.org/repos/fedora-nvidia.repo
#- https://negativo17.org/repos/fedora-multimedia.repo
#- https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-42/atim-starship-fedora-42.repo
